version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: kkevo_postgres
    environment:
      POSTGRES_DB: kkevo_db
      POSTGRES_USER: kkevo_user
      POSTGRES_PASSWORD: kkevo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - kkevo_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: kkevo_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://kkevo_user:kkevo_password@postgres:5432/kkevo_db
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      - postgres
    networks:
      - kkevo_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: kkevo_frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - kkevo_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: kkevo_redis
    ports:
      - "6379:6379"
    networks:
      - kkevo_network

volumes:
  postgres_data:

networks:
  kkevo_network:
    driver: bridge
