[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 4 --worker-class sync --timeout 120 core.wsgi:application"
healthcheckPath = "/api/v1/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
DJANGO_SETTINGS_MODULE = "core.settings.prod"
