# Generated by Django 5.2.4 on 2025-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('ai', 'AI & Machine Learning'), ('devops', 'DevOps & Cloud'), ('consulting', 'Consulting'), ('design', 'UI/UX Design')], max_length=20)),
                ('client', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(default=list)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('team_size', models.CharField(blank=True, max_length=50)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('case_study_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
