# Generated by Django 5.2.4 on 2025-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.IntegerField()),
                ('suffix', models.CharField(blank=True, help_text='e.g., +, %, /7', max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, help_text='Icon identifier', max_length=50)),
                ('color_scheme', models.CharField(default='from-blue-500 to-cyan-500', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Statistic',
                'verbose_name_plural': 'Company Statistics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('devops', 'DevOps & Cloud'), ('ai', 'AI & Machine Learning'), ('consulting', 'Consulting'), ('design', 'UI/UX Design')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
