# Generated by Django 5.2.4 on 2025-08-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_companystats_alter_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon filename or path', max_length=255, null=True),
        ),
    ]
