# Generated by Django 5.2.4 on 2025-08-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='average_project_duration',
            field=models.CharField(blank=True, help_text="Average project duration (e.g., '4-6 weeks')", max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='budget_ranges',
            field=models.JSONField(default=dict, help_text="Budget ranges as JSON. Example: {'Basic': '$3k-$8k', 'Pro': '$10k-$25k'}"),
        ),
        migrations.AddField(
            model_name='service',
            name='complexity_levels',
            field=models.JSONField(default=list, help_text="Complexity levels as JSON array. Example: ['Simple', 'Medium', 'Complex']"),
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables',
            field=models.JSONField(default=list, help_text="What client receives as JSON array. Example: ['Source Code', 'Documentation', 'Training']"),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured services section'),
        ),
        migrations.AddField(
            model_name='service',
            name='max_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum project budget in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='min_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum project budget in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_tiers',
            field=models.JSONField(default=dict, help_text="Pricing tiers as JSON. Example: {'Basic': '$5k', 'Pro': '$15k', 'Enterprise': '$50k'}"),
        ),
        migrations.AddField(
            model_name='service',
            name='success_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Project success rate percentage (e.g., 95.5)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='timeline_estimates',
            field=models.JSONField(default=dict, help_text="Timeline estimates as JSON. Example: {'Basic': '2-4 weeks', 'Pro': '6-8 weeks'}"),
        ),
    ]
