# Generated by Django 5.0 on 2025-08-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_service_average_project_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_headline",
                    models.CharField(
                        default="We Build Software That Moves Markets",
                        help_text="Main headline for the hero section",
                        max_length=200,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Transform your business with cutting-edge software solutions. From web applications to AI-powered systems, we deliver results that drive growth.",
                        help_text="Subtitle text below the main headline",
                    ),
                ),
                (
                    "hero_features",
                    models.JSONField(
                        default=list,
                        help_text="Hero features as JSON array. Example: ['Custom Software Development', 'Web & Mobile Applications']",
                    ),
                ),
                (
                    "cta_headline",
                    models.CharField(
                        default="Ready to Transform Your Business?",
                        help_text="Main CTA headline",
                        max_length=200,
                    ),
                ),
                (
                    "cta_subtitle",
                    models.TextField(
                        default="Let's discuss how our innovative software solutions can drive growth, streamline operations, and create competitive advantages for your business.",
                        help_text="CTA subtitle text",
                    ),
                ),
                (
                    "cta_benefits",
                    models.JSONField(
                        default=list, help_text="CTA benefits as JSON array"
                    ),
                ),
                (
                    "company_phone",
                    models.CharField(
                        default="+1 (555) 123-4567",
                        help_text="Company phone number",
                        max_length=20,
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(
                        default="hello@kkevo.com",
                        help_text="Company email address",
                        max_length=254,
                    ),
                ),
                (
                    "company_address",
                    models.TextField(blank=True, help_text="Company office address"),
                ),
                (
                    "live_chat_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable live chat functionality"
                    ),
                ),
                (
                    "trust_companies",
                    models.JSONField(
                        default=list,
                        help_text="Trusted companies logos as JSON array. Example: ['TechCorp', 'FinanceBank']",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, help_text="Company LinkedIn URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, help_text="Company Twitter URL"),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, help_text="Company GitHub URL"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Configuration",
                "verbose_name_plural": "Company Configuration",
            },
        ),
    ]
