# Generated by Django 5.0 on 2025-08-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_companyconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("web-development", "Web Development"),
                    ("mobile-development", "Mobile Development"),
                    ("cloud-solutions", "Cloud Solutions"),
                    ("ai-ml", "AI & Machine Learning"),
                    ("devops", "DevOps & Infrastructure"),
                    ("consulting", "Consulting"),
                    ("design", "UI/UX Design"),
                ],
                max_length=20,
            ),
        ),
    ]
