# Generated by Django 5.0 on 2025-08-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_alter_service_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Service image", null=True, upload_to="services/"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="image_alt",
            field=models.CharField(
                blank=True,
                help_text="Alt text for service image",
                max_length=255,
                null=True,
            ),
        ),
    ]
