# Generated by Django 5.2.4 on 2025-08-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('team', '0002_teammember_availability_teammember_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Team member assigned to this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teammember'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='budget_range',
            field=models.CharField(blank=True, help_text="Budget range (e.g., '$10k - $25k', '$50k+')", max_length=50),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated project value in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, help_text='Date of last contact attempt', null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiating', 'Negotiating'), ('converted', 'Converted to Project'), ('lost', 'Lost'), ('archived', 'Archived')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='next_follow_up',
            field=models.DateTimeField(blank=True, help_text='When to follow up next', null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for sales team'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='position',
            field=models.CharField(blank=True, help_text='Job title/position', max_length=100),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='project_description',
            field=models.TextField(blank=True, help_text='Detailed description of their project or needs'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='project_size',
            field=models.CharField(blank=True, help_text="Project size (e.g., 'Small', 'Medium', 'Large', 'Enterprise')", max_length=50),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='service_interest',
            field=models.CharField(blank=True, help_text='Which service are they interested in?', max_length=100),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='timeline',
            field=models.CharField(blank=True, help_text="Project timeline (e.g., '3-6 months', 'ASAP')", max_length=50),
        ),
    ]
