# Generated by Django 5.0 on 2025-08-20 15:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_contactsubmission_assigned_to_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactsubmission",
            options={
                "ordering": ["-submitted_at"],
                "verbose_name": "Contact Submission",
                "verbose_name_plural": "Contact Submissions",
            },
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="budget_range",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="estimated_value",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="last_contact_date",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="lead_status",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="next_follow_up",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="position",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="project_description",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="project_size",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="service_interest",
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="first_contacted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="follow_up_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="follow_up_scheduled",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fintech", "Financial Technology"),
                    ("healthcare", "Healthcare"),
                    ("ecommerce", "E-commerce"),
                    ("saas", "SaaS/Software"),
                    ("education", "Education"),
                    ("real-estate", "Real Estate"),
                    ("manufacturing", "Manufacturing"),
                    ("consulting", "Consulting"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="last_contacted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="lead_score",
            field=models.PositiveIntegerField(
                default=0, help_text="Lead scoring from 0-100"
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="project_budget",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under-10k", "Under $10,000"),
                    ("10k-25k", "$10,000 - $25,000"),
                    ("25k-50k", "$25,000 - $50,000"),
                    ("50k-100k", "$50,000 - $100,000"),
                    ("100k-250k", "$100,000 - $250,000"),
                    ("250k+", "$250,000+"),
                    ("not-sure", "Not sure yet"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="source",
            field=models.CharField(
                default="website",
                help_text="Where the contact came from",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("reviewed", "Reviewed"),
                    ("contacted", "Contacted"),
                    ("qualified", "Qualified"),
                    ("proposal_sent", "Proposal Sent"),
                    ("negotiating", "Negotiating"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                    ("spam", "Spam"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="submitted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="team_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("solo", "Solo founder/developer"),
                    ("2-5", "2-5 people"),
                    ("6-10", "6-10 people"),
                    ("11-25", "11-25 people"),
                    ("26-50", "26-50 people"),
                    ("50+", "50+ people"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="urgency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "Low - Just exploring options"),
                    ("medium", "Medium - Planning phase"),
                    ("high", "High - Ready to start soon"),
                    ("critical", "Critical - Need immediate help"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="utm_content",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="utm_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="utm_term",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes and follow-up information"
            ),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="subject",
            field=models.CharField(
                choices=[
                    ("general", "General Inquiry"),
                    ("project", "Project Request"),
                    ("partnership", "Partnership"),
                    ("career", "Career Opportunity"),
                    ("support", "Technical Support"),
                    ("consultation", "Free Consultation"),
                    ("quote", "Get a Quote"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="timeline",
            field=models.CharField(
                blank=True,
                choices=[
                    ("asap", "ASAP (Within 1 month)"),
                    ("1-3-months", "1-3 months"),
                    ("3-6-months", "3-6 months"),
                    ("6-12-months", "6-12 months"),
                    ("12-months+", "12+ months"),
                    ("flexible", "Flexible timeline"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(
                fields=["email", "status"], name="contact_con_email_8a048b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(
                fields=["status", "submitted_at"], name="contact_con_status_efa827_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(
                fields=["lead_score", "submitted_at"],
                name="contact_con_lead_sc_0d10b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(
                fields=["assigned_to", "status"], name="contact_con_assigne_39c83a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(
                fields=["utm_source", "utm_campaign"],
                name="contact_con_utm_sou_d8c900_idx",
            ),
        ),
    ]
