# Generated by Django 5.0 on 2025-08-20 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadMagnetSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("role", models.CharField(blank=True, max_length=100)),
                (
                    "lead_magnet_type",
                    models.CharField(
                        choices=[
                            ("django-saas-checklist", "Django SaaS Checklist"),
                            ("startup-guide", "Startup Guide"),
                            ("tech-stack-guide", "Tech Stack Guide"),
                            ("funding-guide", "Funding Guide"),
                        ],
                        default="django-saas-checklist",
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("social-media", "Social Media"),
                            ("email", "Email Campaign"),
                            ("referral", "Referral"),
                            ("search", "Search Engine"),
                            ("other", "Other"),
                        ],
                        default="website",
                        max_length=50,
                    ),
                ),
                ("form_submitted_at", models.DateTimeField(auto_now_add=True)),
                ("pdf_downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_opened_at", models.DateTimeField(blank=True, null=True)),
                ("is_subscribed_to_newsletter", models.BooleanField(default=True)),
                ("follow_up_scheduled", models.DateTimeField(blank=True, null=True)),
                ("follow_up_completed", models.DateTimeField(blank=True, null=True)),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
                ("utm_term", models.CharField(blank=True, max_length=100)),
                ("utm_content", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "lead_score",
                    models.PositiveIntegerField(
                        default=0, help_text="Lead scoring from 0-100"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New Lead"),
                            ("downloaded", "PDF Downloaded"),
                            ("engaged", "Engaged"),
                            ("qualified", "Qualified"),
                            ("contacted", "Contacted"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lead Magnet Submission",
                "verbose_name_plural": "Lead Magnet Submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "lead_magnet_type"],
                        name="lead_magnet_email_2f102f_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="lead_magnet_status_c45a1c_idx",
                    ),
                    models.Index(
                        fields=["utm_source", "utm_campaign"],
                        name="lead_magnet_utm_sou_0df7ab_idx",
                    ),
                ],
            },
        ),
    ]
