# Generated by Django 5.2.4 on 2025-08-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/hero_images/'),
        ),
    ]
