# Generated by Django 5.2.4 on 2025-08-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL for SEO'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('design', 'Design'), ('development', 'Development'), ('ai-ml', 'AI & Machine Learning'), ('devops', 'DevOps'), ('case-studies', 'Case Studies'), ('industry-news', 'Industry News'), ('tutorials', 'Tutorials'), ('best-practices', 'Best Practices')], default='technology', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_services',
            field=models.JSONField(default=list, help_text='Related services as JSON array of service slugs'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_description',
            field=models.TextField(blank=True, help_text='SEO meta description (max 160 characters)', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_keywords',
            field=models.JSONField(default=list, help_text='SEO keywords as JSON array'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO meta title (max 60 characters)', max_length=60),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
