# Generated by Django 5.0 on 2025-09-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_add_missing_models_only"),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.blogpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_likes', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Blog Post Likes',
                'ordering': ['-liked_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='blog.blogpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_bookmarks', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Blog Post Bookmarks',
                'ordering': ['-bookmarked_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='blogpostlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_post_user_like'),
        ),
        migrations.AddConstraint(
            model_name='blogpostbookmark',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_post_user_bookmark'),
        ),
    ]
