# Generated by Django 5.0 on 2025-09-01 20:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_auto_20250901_2217"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPostShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("email", "Email"),
                            ("copy_link", "Copy Link"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Blog Post Shares",
                "ordering": ["-shared_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogPostView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.CharField(blank=True, max_length=200)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Blog Post Views",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-is_featured", "order", "-published_at"],
                "verbose_name_plural": "Blog Posts",
            },
        ),
        migrations.AlterModelOptions(
            name="blogtag",
            options={"ordering": ["name"], "verbose_name_plural": "Blog Tags"},
        ),
        migrations.RemoveConstraint(
            model_name="blogpostbookmark",
            name="unique_post_user_bookmark",
        ),
        migrations.RemoveConstraint(
            model_name="blogpostlike",
            name="unique_post_user_like",
        ),
        migrations.RemoveField(
            model_name="blogcategory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="blogcategory",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=36, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="published_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="blogpostbookmark",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_bookmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blogpostlike",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blogpostbookmark",
            unique_together={("post", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="blogpostlike",
            unique_together={("post", "user")},
        ),
        migrations.AddField(
            model_name="blogpostshare",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="blog.blogpost",
            ),
        ),
        migrations.AddField(
            model_name="blogpostshare",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_shares",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blogpostview",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="blog.blogpost",
            ),
        ),
        migrations.AddField(
            model_name="blogpostview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
