# Generated by Django 5.2.4 on 2025-08-24 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcategory_alter_blogpost_options_and_more'),
        ('team', '0001_initial'),
    ]

    operations = [
        # Add missing fields to BlogPost
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        
        # Add user field to engagement models
        migrations.AddField(
            model_name='blogpostview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_views', to='auth.user'),
        ),
        migrations.AddField(
            model_name='blogpostlike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_likes', to='auth.user'),
        ),
        migrations.AddField(
            model_name='blogpostbookmark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_bookmarks', to='auth.user'),
        ),
        migrations.AddField(
            model_name='blogpostshare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_shares', to='auth.user'),
        ),
    ]
