# Generated by Django 5.2.4 on 2025-08-25 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_auto_20250824_2044"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="canonical_url",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="difficulty_level",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="hero_image",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=32, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="reading_time",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="related_services",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="seo_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="seo_keywords",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="seo_title",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="blogpostbookmark",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_bookmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blogpostlike",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blogpostshare",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_shares",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="blogpostview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blogpostbookmark",
            unique_together={("post", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="blogpostlike",
            unique_together={("post", "user")},
        ),
    ]
