# Generated by Django 5.2.4 on 2025-11-24 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_anonymous_progress(apps, schema_editor):
    UserReadingProgress = apps.get_model("blog", "UserReadingProgress")
    UserReadingProgress.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_allow_anonymous_reading_progress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_anonymous_progress, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="userreadingprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
