# Generated by Django 5.2.4 on 2025-08-25 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_blogpost_canonical_url_alter_blogpost_category_and_more"),
    ]

    operations = []
