# Generated by Django 5.0 on 2025-08-26 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_update_blog_models"),
        ("team", "0002_teammember_availability_teammember_certifications_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogcategory",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="blogpostshare",
            name="share_type",
        ),
        migrations.RemoveField(
            model_name="blogpostshare",
            name="user_agent",
        ),
        migrations.RemoveField(
            model_name="blogpostview",
            name="session_key",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="blog_posts",
                to="team.teammember",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                    ("scheduled", "Scheduled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
