# Generated by Django 5.0 on 2025-08-26 13:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_remove_blogcategory_icon_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("color", models.CharField(default="#6B7280", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Blog Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPostAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_views", models.PositiveIntegerField(default=0)),
                ("returning_visitors", models.PositiveIntegerField(default=0)),
                (
                    "bounce_rate",
                    models.FloatField(
                        default=0.0, help_text="Bounce rate as percentage"
                    ),
                ),
                (
                    "average_time_on_page",
                    models.FloatField(default=0.0, help_text="Average time in seconds"),
                ),
                (
                    "average_scroll_depth",
                    models.FloatField(
                        default=0.0, help_text="Average scroll depth as percentage"
                    ),
                ),
                (
                    "completion_rate",
                    models.FloatField(
                        default=0.0, help_text="Completion rate as percentage"
                    ),
                ),
                (
                    "social_shares",
                    models.JSONField(default=dict, help_text="Shares by platform"),
                ),
                (
                    "social_clicks",
                    models.JSONField(default=dict, help_text="Clicks by platform"),
                ),
                ("search_impressions", models.PositiveIntegerField(default=0)),
                ("search_clicks", models.PositiveIntegerField(default=0)),
                ("ctr", models.FloatField(default=0.0, help_text="Click-through rate")),
                ("lead_generations", models.PositiveIntegerField(default=0)),
                ("newsletter_signups", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Blog Post Analytics",
            },
        ),
        migrations.CreateModel(
            name="BlogPostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("is_moderated", models.BooleanField(default=False)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("moderation_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog.blogpostcomment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blogpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Blog Post Comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserReadingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "time_spent",
                    models.PositiveIntegerField(
                        default=0, help_text="Time spent in seconds"
                    ),
                ),
                (
                    "last_position",
                    models.PositiveIntegerField(
                        default=0, help_text="Last scroll position"
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_read_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to="blog.blogpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Reading Progress",
                "ordering": ["-last_read_at"],
                "unique_together": {("user", "post")},
            },
        ),
    ]
