# Generated by Django 5.0 on 2025-08-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("summary", models.TextField()),
                ("description", models.TextField()),
                ("client_name", models.CharField(max_length=100)),
                ("client_industry", models.CharField(max_length=100)),
                ("client_size", models.CharField(blank=True, max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("web", "Web Development"),
                            ("mobile", "Mobile Development"),
                            ("ai", "AI & Machine Learning"),
                            ("devops", "DevOps & Cloud"),
                            ("consulting", "Consulting"),
                            ("design", "UI/UX Design"),
                            ("ecommerce", "E-commerce"),
                            ("healthcare", "Healthcare"),
                            ("finance", "Finance"),
                            ("education", "Education"),
                        ],
                        max_length=20,
                    ),
                ),
                ("project_duration", models.CharField(max_length=50)),
                ("team_size", models.CharField(max_length=50)),
                ("budget_range", models.CharField(blank=True, max_length=50)),
                (
                    "challenge",
                    models.TextField(
                        help_text="What business problems did the client face?"
                    ),
                ),
                (
                    "solution",
                    models.TextField(help_text="How did we solve these challenges?"),
                ),
                (
                    "approach",
                    models.TextField(
                        help_text="What was our methodology and approach?"
                    ),
                ),
                (
                    "technologies",
                    models.JSONField(
                        default=list, help_text="List of technologies used"
                    ),
                ),
                (
                    "tools",
                    models.JSONField(
                        default=list, help_text="List of tools and frameworks used"
                    ),
                ),
                (
                    "business_objectives",
                    models.JSONField(
                        default=list, help_text="Business objectives as JSON array"
                    ),
                ),
                (
                    "key_results",
                    models.JSONField(
                        default=list, help_text="Key results achieved as JSON array"
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict, help_text="Quantifiable metrics and KPIs"
                    ),
                ),
                (
                    "roi",
                    models.CharField(
                        blank=True,
                        help_text="ROI or business impact summary",
                        max_length=100,
                    ),
                ),
                ("client_testimonial", models.TextField(blank=True)),
                ("client_contact_name", models.CharField(blank=True, max_length=100)),
                ("client_contact_role", models.CharField(blank=True, max_length=100)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="case_studies/"),
                ),
                ("gallery_images", models.JSONField(blank=True, default=list)),
                ("live_url", models.URLField(blank=True)),
                (
                    "case_study_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="case_studies/pdfs/"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Case Study",
                "verbose_name_plural": "Case Studies",
                "ordering": ["order", "-published_at", "-created_at"],
            },
        ),
    ]
