# Generated by Django 5.0 on 2025-08-20 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("case_studies", "0001_initial"),
    ]

    operations = []
