# Generated by Django 5.2.4 on 2025-08-14 20:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('ceo', 'CEO'), ('cto', 'CTO'), ('developer', 'Developer'), ('designer', 'Designer'), ('devops', 'DevOps Engineer'), ('pm', 'Project Manager'), ('qa', 'QA Engineer'), ('intern', 'Intern')], max_length=20)),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team/avatars/')),
                ('social_links', models.JSONField(default=dict, help_text='Social media links as JSON. Example: {"linkedin": "url", "github": "url"}')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
