# Generated by Django 5.2.4 on 2025-08-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('unavailable', 'Unavailable'), ('on_leave', 'On Leave')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='certifications',
            field=models.JSONField(default=list, help_text='Professional certifications as JSON array'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='current_projects',
            field=models.JSONField(default=list, help_text='Current project assignments as JSON array'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='current_workload',
            field=models.PositiveIntegerField(default=0, help_text='Current workload percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of professional experience'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate in USD', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='max_workload',
            field=models.PositiveIntegerField(default=100, help_text='Maximum workload capacity (0-100)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skill_levels',
            field=models.JSONField(default=dict, help_text="Skill proficiency levels as JSON. Example: {'React': 'Expert', 'Python': 'Advanced'}"),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills',
            field=models.JSONField(default=list, help_text="Technical skills as JSON array. Example: ['React', 'Python', 'AWS']"),
        ),
        migrations.AddField(
            model_name='teammember',
            name='specializations',
            field=models.JSONField(default=list, help_text='Areas of specialization as JSON array'),
        ),
    ]
